export { default as School1 } from './school-1.svg'
// export {default as School2} from './school-2.jpg'
export { default as School3 } from './school-3.jpg'
export { default as School4 } from './school-4.jpeg'
export { default as School5 } from './school-5.svg'
export { default as School6 } from './school-6.svg'
export { default as School7 } from './school-7.jpg'
export { default as School8 } from './school-8.svg'
export { default as School9 } from './school-9.jpeg'
export { default as School10 } from './school-10.svg'
// export {default as School11} from './school-11.jpg'
export { default as School12 } from './school-12.svg'
export { default as School13 } from './school-13.jpeg'
export { default as School14 } from './school-14.jpg'
export { default as School15 } from './school-15.jpg'
// export {default as School16} from './school-16.jpg'
export { default as School17 } from './school-17.svg'
export { default as School18 } from './school-18.svg'
export { default as School19 } from './school-19.jpg'
export { default as School20 } from './school-20.jpg'
export { default as School21 } from './school-21.svg'
export { default as School22 } from './school-22.svg'
export { default as School23 } from './school-23.jpeg'
export { default as School24 } from './school-24.svg'
export { default as School25 } from './school-25.jpg'
export { default as School26 } from './school-26.jpg'
export { default as School27 } from './school-27.jpg'
export { default as SchoolPlaceholder } from './school-placeholder.jpeg'
export { default as School28 } from './school28.jpg'
export { default as School29 } from './school29.jpg'
