import {
  School1,
  School10,
  School12,
  School13,
  School14,
  School15,
  School17,
  School18,
  School19,
  School20,
  School21,
  School22,
  School23,
  School24,
  School25,
  School26,
  School27,
  School3,
  School4,
  School5,
  School6,
  School7,
  School8,
  School9,
  School28,
  School29,
} from '@assets/images/schools'

export const data = [
  {
    schoolName: 'A.N.D High School',
    city: 'Chapra',
    state: 'Bihar',
    uptoClass: 'Upto Class 12th',
    strength: 2500,
    establishmentYear: 1994,
    image: School1,
  },
  {
    schoolName: 'Presidency School and College',
    city: 'Pratapgarh',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 500,
    establishmentYear: 1990,
    image: {},
  },
  {
    schoolName: 'Divine public senior secondary school',
    city: 'Maharajganj',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1000,
    establishmentYear: 2007,
    image: School3,
  },
  {
    schoolName: 'Symbiosis School For Excellence',
    city: 'Mathura',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1700,
    establishmentYear: 2014,
    image: School4,
  },
  {
    schoolName: 'Lotus Valley School',
    city: 'Mandsaur',
    state: 'MP',
    uptoClass: 'Upto Class 12th',
    strength: 1800,
    establishmentYear: 2006,
    image: School5,
  },
  {
    schoolName: 'KDPS School',
    city: 'Narela, Delhi',
    state: 'Delhi',
    uptoClass: 'Upto Class 12th',
    strength: 2000,
    establishmentYear: 2016,
    image: School6,
  },
  {
    schoolName: 'Boston Public School',
    city: 'Agra',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 2000,
    establishmentYear: 2008,
    image: School7,
  },
  {
    schoolName: 'Seth M.R. Jaipuria Main School Malwan, Fatehpur',
    city: 'Fatehpur',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 2000,
    establishmentYear: 2017,
    image: School8,
  },
  {
    schoolName: 'MP Public School',
    city: 'Maharajganj',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1500,
    establishmentYear: 2010,
    image: School9,
  },
  {
    schoolName: 'Roorkee public school',
    city: 'Roorkee',
    state: 'Uttarakhand',
    uptoClass: 'Upto Class 12th',
    strength: 1500,
    establishmentYear: 1998,
    image: School10,
  },
  {
    schoolName: "St Mary's School",
    city: 'Saharanpur',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1800,
    establishmentYear: 1968,
    image: {},
  },
  {
    schoolName: 'The wembley International School',
    city: 'Siwan',
    state: 'Bihar',
    uptoClass: 'Upto Class 12th',
    strength: 800,
    establishmentYear: 2017,
    image: School12,
  },
  {
    schoolName: 'GS Public School',
    city: 'Jaunpur',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1000,
    establishmentYear: 2012,
    image: School13,
  },
  {
    schoolName: 'K.D. Public School',
    city: 'DEORIA',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 2000,
    establishmentYear: 2008,
    image: School14,
  },
  {
    schoolName: 'Unique Science Academy Senior Secondary School',
    city: 'BASTI',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 2500,
    establishmentYear: 2004,
    image: School15,
  },
  {
    schoolName: 'Rashtra Dev International Academy',
    city: 'Saharanpur',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1500,
    establishmentYear: 1990,
    image: {}, // School16
  },
  {
    schoolName: 'TRB Senior Secondary School',
    city: 'Sivsagar',
    state: 'Assam',
    uptoClass: 'Upto Class 12th',
    strength: 500,
    establishmentYear: 2014,
    image: School17,
  },
  {
    schoolName: 'Aadarsh Public School',
    city: 'Charki Dadri',
    state: 'Haryana',
    uptoClass: 'Upto Class 12th',
    strength: 700,
    establishmentYear: 2010,
    image: School18,
  },
  {
    schoolName: 'Sri Radha Bihari Public School',
    city: 'Hathras',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 800,
    establishmentYear: 2016,
    image: School19,
  },
  {
    schoolName: 'Trident Academy Senior Secondary school',
    city: 'Rampur',
    state: 'Assam',
    uptoClass: 'Upto Class 12th',
    strength: 150,
    establishmentYear: 2019,
    image: School20,
  },
  {
    schoolName: 'KD International',
    city: 'Pilkhuwa',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 600,
    establishmentYear: 2010,
    image: School21,
  },
  {
    schoolName: 'Holy Child Public School',
    city: 'Rewari',
    state: 'Haryana',
    uptoClass: 'Upto Class 12th',
    strength: 3000,
    establishmentYear: 1979,
    image: School22,
  },
  {
    schoolName: 'Jaycees Public School',
    city: 'Rudarpur',
    state: 'Uttrakhand',
    uptoClass: 'Upto Class 12th',
    strength: 4000,
    establishmentYear: 1986,
    image: School23,
  },
  {
    schoolName: 'DPS Rudrapur',
    city: 'Rudrapur',
    state: 'Uttrakhand',
    uptoClass: 'Upto Class 12th',
    strength: 1500,
    establishmentYear: 2017,
    image: School24,
  },
  {
    schoolName: 'Sacred Heart School',
    city: 'Katni',
    state: 'MP',
    uptoClass: 'Upto Class 12th',
    strength: 1030,
    establishmentYear: 1980,
    image: School25,
  },
  {
    schoolName: 'Sri Agrasen School',
    city: 'Bhurkhunda',
    state: 'Jharkhand',
    uptoClass: 'Upto Class 12th',
    strength: 1200,
    establishmentYear: 2012,
    image: School26,
  },
  {
    schoolName: 'Seven Hills Inter college',
    city: 'Etawah',
    state: 'Uttar Pradesh',
    uptoClass: 'Upto Class 12th',
    strength: 1500,
    establishmentYear: 1990,
    image: School27,
  },
  {
    schoolName: 'Sanskar the Gurukul International School',
    city: 'Bastar',
    state: 'Chhattisgarh',
    uptoClass: 'Upto Class 12th',
    strength: 475,
    establishmentYear: 2005,
    image: School28,
  },
  {
    schoolName: 'Happy Evergreen Sr. Sec. School',
    city: 'Mahendragarh',
    state: 'Haryana',
    uptoClass: 'Upto Class 12th',
    strength: 2500,
    establishmentYear: 1981,
    image: School29,
  },
]
