export { default as HomeHeader } from './home/header/HomeHeader'
export { default as BatchList } from './home/batches/batch-list/BatchList'
export { default as DemoVideo } from './home/demo-video/DemoVideo'
export { default as TestimonialSection } from './home/testimonials/testimonial-section/TestimonialSection'
export { default as ShareNow } from './home/share-now/ShareNow'
